name: Create Month Invoices

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  send_post:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret length
        run: |
          if [ -z "${{ secrets.AUTOMATION_TOKEN }}" ]; then
            echo "Secret AUTOMATION_TOKEN is empty or not set"
          else
            echo "Token length: ${#AUTOMATION_TOKEN}"
          fi
        env:
          AUTOMATION_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
