name: Create Month Invoices

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  send_post:
    runs-on: ubuntu-latest
    steps:
    - name: Check secret access
      run: echo "Token length: ${{ secrets.AUTOMATION_TOKEN && secrets.AUTOMATION_TOKEN.length }}"
