name: Create Month Invoices

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  send_post:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request with curl
        env:
          AUTOMATION_URL: http://localhost:3000/automations/create-invoices
          AUTOMATION_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
        run: |
          response=$(curl -s -X POST "$AUTOMATION_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $AUTOMATION_TOKEN")
          echo "Response: $response"
