name: Create Month Invoices

on:
  schedule:
    - cron: '0 0 1 * *'  # todo dia 1 às 00:00 UTC
  workflow_dispatch:

jobs:
  send_post:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        id: post
        uses: fjogeleit/http-request-action@v1.15.1
        with:
          url: ${{ secrets.AUTOMATION_URL }}
          method: 'POST'
          customHeaders: |
            [
              { "name": "Content-Type", "value": "application/json" },
              { "name": "Authorization", "value": "Bearer ${{ secrets.AUTOMATION_TOKEN }}" }
            ]

      - name: Print response
        run: |
          echo "Response:"
          echo '${{ steps.post.outputs.response }}' | jq .

