name: Create Month Invoices

on:
  schedule:
    - cron: '0 7 1 * *'  # 04:00 BRT (07:00 UTC)
  workflow_dispatch:

jobs:
  send_post:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request with curl
        env:
          AUTOMATION_URL: ${{ secrets.AUTOMATION_URL }}
          AUTOMATION_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
        run: |
          response=$(curl -s -X POST "$AUTOMATION_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $AUTOMATION_TOKEN")
          echo "Response: $response"
